theme: minima
title: ~~CodeYoungster~~
author: Code-Youngster
email: codeyoungster@gmail.com
description: Noob today, Geek next week It's whatever

 social links
twitter_username: ~~twitter~~ # DO NOT include the @ character, or else the build will fail!
github_username:  Code-Youngster # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
